load("@bazel-zig-cc//toolchain/platform:defs.bzl", "declare_platforms")
load("@bazel-zig-cc//toolchain/platform:defs.bzl", "declare_libc_aware_platforms")

package(
    default_visibility = ["//visibility:public"],
)

declare_platforms()
declare_libc_aware_platforms()
